# Generated by Django 4.2.6 on 2023-10-17 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_drink_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.drink')),
            ],
        ),
    ]
