# Generated by Django 4.2.6 on 2023-10-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='instructions',
            field=models.TextField(max_length=350),
        ),
    ]
